version: '3.5'

services:
  Aurora.Platform.Applications.API:
    image: ${DOCKER_REGISTRY-}aurora/platform-applications-api:1.0
    build:
      context: .
      dockerfile: Services/Applications/Aurora.Platform.Applications.API/Dockerfile
    container_name: Aurora.Platform.Applications.API
    networks:
      - aurora-platform

  Aurora.Platform.Security.API:
    image: ${DOCKER_REGISTRY-}aurora/platform-security-api:1.0
    build:
      context: .
      dockerfile: Services/Security/Aurora.Platform.Security.API/Dockerfile
    container_name: Aurora.Platform.Security.API
    networks:
      - aurora-platform

networks:
  aurora-platform:
    name: aurora-platform